/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlaygroundsRouteImport } from './routes/playgrounds'
import { Route as InstrumentsRouteImport } from './routes/instruments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewsNewRouteImport } from './routes/reviews.new'
import { Route as PlaygroundsNewRouteImport } from './routes/playgrounds_.new'
import { Route as PlaygroundsPlaygroundIdRouteImport } from './routes/playgrounds_.$playgroundId'
import { Route as PlaygroundsPlaygroundIdEditRouteImport } from './routes/playgrounds_.$playgroundId_.edit'

const PlaygroundsRoute = PlaygroundsRouteImport.update({
  id: '/playgrounds',
  path: '/playgrounds',
  getParentRoute: () => rootRouteImport,
} as any)
const InstrumentsRoute = InstrumentsRouteImport.update({
  id: '/instruments',
  path: '/instruments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsNewRoute = ReviewsNewRouteImport.update({
  id: '/reviews/new',
  path: '/reviews/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundsNewRoute = PlaygroundsNewRouteImport.update({
  id: '/playgrounds_/new',
  path: '/playgrounds/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundsPlaygroundIdRoute = PlaygroundsPlaygroundIdRouteImport.update({
  id: '/playgrounds_/$playgroundId',
  path: '/playgrounds/$playgroundId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundsPlaygroundIdEditRoute =
  PlaygroundsPlaygroundIdEditRouteImport.update({
    id: '/playgrounds_/$playgroundId_/edit',
    path: '/playgrounds/$playgroundId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/instruments': typeof InstrumentsRoute
  '/playgrounds': typeof PlaygroundsRoute
  '/playgrounds/$playgroundId': typeof PlaygroundsPlaygroundIdRoute
  '/playgrounds/new': typeof PlaygroundsNewRoute
  '/reviews/new': typeof ReviewsNewRoute
  '/playgrounds/$playgroundId/edit': typeof PlaygroundsPlaygroundIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/instruments': typeof InstrumentsRoute
  '/playgrounds': typeof PlaygroundsRoute
  '/playgrounds/$playgroundId': typeof PlaygroundsPlaygroundIdRoute
  '/playgrounds/new': typeof PlaygroundsNewRoute
  '/reviews/new': typeof ReviewsNewRoute
  '/playgrounds/$playgroundId/edit': typeof PlaygroundsPlaygroundIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/instruments': typeof InstrumentsRoute
  '/playgrounds': typeof PlaygroundsRoute
  '/playgrounds_/$playgroundId': typeof PlaygroundsPlaygroundIdRoute
  '/playgrounds_/new': typeof PlaygroundsNewRoute
  '/reviews/new': typeof ReviewsNewRoute
  '/playgrounds_/$playgroundId_/edit': typeof PlaygroundsPlaygroundIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/instruments'
    | '/playgrounds'
    | '/playgrounds/$playgroundId'
    | '/playgrounds/new'
    | '/reviews/new'
    | '/playgrounds/$playgroundId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/instruments'
    | '/playgrounds'
    | '/playgrounds/$playgroundId'
    | '/playgrounds/new'
    | '/reviews/new'
    | '/playgrounds/$playgroundId/edit'
  id:
    | '__root__'
    | '/'
    | '/instruments'
    | '/playgrounds'
    | '/playgrounds_/$playgroundId'
    | '/playgrounds_/new'
    | '/reviews/new'
    | '/playgrounds_/$playgroundId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InstrumentsRoute: typeof InstrumentsRoute
  PlaygroundsRoute: typeof PlaygroundsRoute
  PlaygroundsPlaygroundIdRoute: typeof PlaygroundsPlaygroundIdRoute
  PlaygroundsNewRoute: typeof PlaygroundsNewRoute
  ReviewsNewRoute: typeof ReviewsNewRoute
  PlaygroundsPlaygroundIdEditRoute: typeof PlaygroundsPlaygroundIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/playgrounds': {
      id: '/playgrounds'
      path: '/playgrounds'
      fullPath: '/playgrounds'
      preLoaderRoute: typeof PlaygroundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instruments': {
      id: '/instruments'
      path: '/instruments'
      fullPath: '/instruments'
      preLoaderRoute: typeof InstrumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/new': {
      id: '/reviews/new'
      path: '/reviews/new'
      fullPath: '/reviews/new'
      preLoaderRoute: typeof ReviewsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playgrounds_/new': {
      id: '/playgrounds_/new'
      path: '/playgrounds/new'
      fullPath: '/playgrounds/new'
      preLoaderRoute: typeof PlaygroundsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playgrounds_/$playgroundId': {
      id: '/playgrounds_/$playgroundId'
      path: '/playgrounds/$playgroundId'
      fullPath: '/playgrounds/$playgroundId'
      preLoaderRoute: typeof PlaygroundsPlaygroundIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playgrounds_/$playgroundId_/edit': {
      id: '/playgrounds_/$playgroundId_/edit'
      path: '/playgrounds/$playgroundId/edit'
      fullPath: '/playgrounds/$playgroundId/edit'
      preLoaderRoute: typeof PlaygroundsPlaygroundIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InstrumentsRoute: InstrumentsRoute,
  PlaygroundsRoute: PlaygroundsRoute,
  PlaygroundsPlaygroundIdRoute: PlaygroundsPlaygroundIdRoute,
  PlaygroundsNewRoute: PlaygroundsNewRoute,
  ReviewsNewRoute: ReviewsNewRoute,
  PlaygroundsPlaygroundIdEditRoute: PlaygroundsPlaygroundIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
